### ISSUE TITLE
photo upload not working 

### ISSUE THREAD

**Issue by alexferra** [stanvanrooy/instauto#134]
I'm using the upload example. It used to work, now I get this. I have the latest version

Traceback (most recent call last):
  File "C:/Users/Alefe/Downloads/bot/instauto-master/MINE/upload_Alejandro.py", line 54, in <module>
    resp2 = client2.post_post(post, 80)
  File "C:\Python38\lib\site-packages\instauto\api\actions\post.py", line 138, in post_post
    return self._request('media/configure/', Method.POST, data=as_dict, headers=headers, signed=True)
  File "C:\Python38\lib\site-packages\instauto\api\actions\request.py", line 233, in _request
    self._check_response_for_errors(resp)
  File "C:\Python38\lib\site-packages\instauto\api\actions\request.py", line 274, in _check_response_for_errors
    raise BadResponse("Received a non-200 response from Instagram")
instauto.api.exceptions.BadResponse: Received a non-200 response from Instagram

**Comment by Anteeiiku** [comment]
Hi, Are you using some kind of proxy/VPN ?

**Comment by alexferra** [comment]
Im not, but it used to work before

**Comment by stanvanrooy** [comment]
Could you try it with debugging on, and post the logs here or send them to me at stan@rooy.dev
