### ISSUE TITLE
Connection aborted upon posting an image to Instagram after a period of time staying logged in- Error 10054

### ISSUE THREAD

**Issue by hmdz105** [stanvanrooy/instauto#145]
**Describe the bug**
After staying logged in and uploading images for sometime using instauto (like two hours), the connection is forcibly closed by remote server when trying to post a new image to Instagram.

**To Reproduce**
1. Log into an Instagram account using instauto for two hours or more. Stay logged in.
2. Post 3-4 images to your account using post_post() method on a regular basis (like every 15 minutes)
3. Keep the program's main loop posting an image on a regular basis. (using a time counter)
4. Upon the third/forth post attempt, if a specific amount of time has passed since the first log-in, the following error is raised:

**Expected behavior**
Uploading images should finish properly.

**Debug output**

Traceback (most recent call last):
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Program Files\Python39\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python39\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python39\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python39\lib\http\client.py", line 1049, in _send_output
    self.send(chunk)
  File "C:\Program Files\Python39\lib\http\client.py", line 971, in send
    self.sock.sendall(data)
  File "C:\Program Files\Python39\lib\ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "C:\Program Files\Python39\lib\ssl.py", line 1173, in send
    return self._sslobj.write(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\urllib3\util\retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Program Files\Python39\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python39\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python39\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python39\lib\http\client.py", line 1049, in _send_output
    self.send(chunk)
  File "C:\Program Files\Python39\lib\http\client.py", line 971, in send
    self.sock.sendall(data)
  File "C:\Program Files\Python39\lib\ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "C:\Program Files\Python39\lib\ssl.py", line 1173, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\instauto\api\actions\request.py", line 214, in _request
    resp = self._session.post(url, data, headers=headers)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Traceback (most recent call last):
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Program Files\Python39\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python39\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python39\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python39\lib\http\client.py", line 1049, in _send_output
    self.send(chunk)
  File "C:\Program Files\Python39\lib\http\client.py", line 971, in send
    self.sock.sendall(data)
  File "C:\Program Files\Python39\lib\ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "C:\Program Files\Python39\lib\ssl.py", line 1173, in send
    return self._sslobj.write(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\urllib3\util\retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Program Files\Python39\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python39\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python39\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python39\lib\http\client.py", line 1049, in _send_output
    self.send(chunk)
  File "C:\Program Files\Python39\lib\http\client.py", line 971, in send
    self.sock.sendall(data)
  File "C:\Program Files\Python39\lib\ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "C:\Program Files\Python39\lib\ssl.py", line 1173, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\DB\Dropbox\instagramPrjct\Initial tests-v0.2\InstagramUploader.py", line 124, in <module>
    resp = client.post_post(post, 100)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\instauto\api\actions\post.py", line 133, in post_post
    as_dict = self._upload_image(obj, quality)[1]
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\instauto\api\actions\post.py", line 114, in _upload_image
    resp = self._request(f'https://i.instagram.com/rupload_igphoto/{headers["x-entity-name"]}', Method.POST,
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\instauto\api\actions\request.py", line 225, in _request
    raise e
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\instauto\api\actions\request.py", line 214, in _request
    resp = self._session.post(url, data, headers=headers)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

**Comment by stanvanrooy** [comment]
Could you add the console output with debugging logging enabled

**Comment by hmdz105** [comment]
**Again the connection was aborted after 1/5 hours and 4 post uploads**. The last uploaded post **has no caption**! 
Here is the console output with debugging logging enabled:

(Truncated from the beginning. Probably the uploaded image data is truncated:) 

......\xc9\x90\xb2\xe0g99\xe6\x83a\xbb9\xdb\x93\x9f\xf7\x9b\x1d3\xebA\x8c\xfe\'\xf2\xfc\x91\x11@Fz\x0cg\x1d\x7f\xaf\xa5\x04\x95\x9e\x1c\x93\xd0\x1e\x9d\xff\x00>\xbd\x7f\xcf\xb5\x00Uh\x0fB\x13\xa7bq\xff\x00\xa0Pi\x19I\xbbh\xfa\xeb\xa7\xe5\xfeE)!\xe9\xc8\xef\x8e\xbc~\xbdz{PhR\x92\xd8\xe7\x1c\x0e\xfdO\x03\xd3\xee\xff\x00\x9f\xe4\x01E\xe0 \xf6\xfc\t\x1f\xfb/\xf8P\x04\x1eW9\xe3?S\xf4\xa0\x00F\xc3\xbf>\xcc\xc3\xfa\x9a\x00\x99cb\xa3,?\xf1\xef\xf1\xfe\xb4\x00\xa8\xad\x8e\xa0}\t\xfe|\xe7\xad\x079<[\x8f#\x1d\x0f\\\xfa\xd0t\x1f\xff\xd9'
HEADERS: {'x-cm-bandwidth-kbps': '-1.000', 'x-cm-latency': '-1.000', 'x-ads-opt-out': '0', 'x-ig-app-locale': 'nl_NL', 'x-ig-app-startup-country': 'NL', 'x-ig-device-locale': 'nl_NL', 'x-ig-mapped-locale': 'nl_NL', 'x-ig-connection-speed': '1117kbps', 'x-ig-bandwidth-speed-kbps': '5000.307', 'x-ig-bandwidth-totalbytes-b': '0', 'x-ig-bandwidth-totaltime-ms': '0', 'x-ig-www-claim': '0', 'x-ig-device-id': '14fb10a7-5d7d-460f-9c55-ca1b8281f561', 'x-ig-android-id': 'android-5d7d460f9c55ca1b', 'x-ig-connection-type': 'WIFI', 'x-ig-capabilities': '3brTvw8=', 'x-ig-app-id': '567067343352427', 'user-agent': 'Instagram 148.0.0.33.121 Android (29/10; 560dpi; 1440x2891; samsung; SM-973F; SM-973F; exynos9820; nl_NL; 227298996)', 'accept-language': 'nl_NL, en_US', 'x-mid': 'YDIANQABAAGFh9VdBtxf8HaB_1rV', 'ig-u-rur': 'FTW', 'accept-encoding': 'gzip', 'x-fb-http-engine': 'Liger', 'authorization': 'Bearer IGT:2:eyJkc191c2VyX2lkIjoiNDU3NjA2Mjc0MTIiLCJzZXNzaW9uaWQiOiI0NTc2MDYyNzQxMiUzQTE4SkEwNENQY2ptY3l5JTNBMTAiLCJzaG91bGRfdXNlX2hlYWRlcl9vdmVyX2Nvb2tpZXMiOmZhbHNlfQ==', 'connection': 'close', 'x-pigeon-session-id': 'a2fcae2a-3478-4aa4-a522-3208f83fcb8a', 'x-pigeon-rawclienttime': '1613894422.538', 'x-bloks-version-id': '5da07fc1b20eb4c7d1b2e6146ee5f197072cbbd193d2d1eb3bb4e825d3c39e28', 'x-bloks-is-layout-rtl': 'False', 'host': 'i.instagram.com', 'x-fb-photo-waterfall-id': 'b71febc3-cd13-474d-9c20-4bb65f9b6a46', 'x-entity-length': '492093', 'x-entity-name': '1613961556_0_7876495116', 'x-instagram-rupload-params': '{"upload_id": "1613961556", "media_type": 1, "retry_context": "{\\"num_reupload\\": 0, \\"num_step_auto_retry\\": 0, \\"num_step_manual_retry\\": 0}", "xsharing_user_ids": "[]", "image_compression": "{\\"lib_name\\": \\"moz\\", \\"lib_version\\": \\"3.1.m\\", \\"quality\\": \\"95\\"}", "is_sidecar": "0"}', 'x-entity-type': 'image/jpg', 'offset': '0', 'scene_capture_type': 'standard', 'creation_logger_session_id': 'af6ad779-7291-492f-9a16-f6acd2484143', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8', 'Authorization': 'REMOVED PII'}
RESPONSE: b'{"upload_id":"1613961556","xsharing_nonces":{},"status":"ok"}'
******************** END REQUEST ********************
DEBUG:urllib3.connectionpool:Resetting dropped connection: i.instagram.com
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2021-02-21 11:39:53.635676+03:30 (in 356.851560 seconds)
INFO:apscheduler.executors.default:Running job "AuthenticationMixin._refresh_session (trigger: interval[0:05:00], next run at: 2021-02-21 11:39:53 +0330)" (scheduled at 2021-02-21 11:33:56.768638+03:30)
INFO:apscheduler.executors.default:Job "AuthenticationMixin._refresh_session (trigger: interval[0:05:00], next run at: 2021-02-21 11:39:53 +0330)" executed successfully
ERROR:instauto.api.actions.request:Exception while sending request to https://i.instagram.com/api/v1/media/configure/ with data: 
 {'ig_sig_key_version': '4', 'signed_body': 'SIGNATURE.{"suggested_venue_position": -1, "multi_sharing": "-1", "caption": "\\u200c \\n\\n+-------+------+\\n|  \\u0627\\u0631\\u0632  | \\u0642\\u06cc\\u0645\\u062a |\\n+-------+------+\\n| \\u0622\\u0628\\u0634\\u062f\\u0647 | 4772 |\\n+-------+------+", "size": [886, 1070], "upload_id": "1613961556", "timezone_offset": "12600", "scene_capture_type": "", "media_folder": "Pictures", "source_type": 4, "edits": {"crop_original_size": [886, 1070], "crop_center": [0.0, 0.0], "crop_zoom": 1.0}, "extra": {"source_width": 886, "source_height": 1070}, "device": {"manufacturer": "samsung", "model": "beyond1", "android_version": "29", "android_release": "10"}, "device_id": "android-5d7d460f9c55ca1b"}'}
Traceback (most recent call last):
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Program Files\Python39\lib\http\client.py", line 331, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "C:\Program Files\Python39\lib\http\client.py", line 216, in parse_headers
    line = fp.readline(_MAXLINE + 1)
  File "C:\Program Files\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Program Files\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Program Files\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\urllib3\util\retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Program Files\Python39\lib\http\client.py", line 331, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "C:\Program Files\Python39\lib\http\client.py", line 216, in parse_headers
    line = fp.readline(_MAXLINE + 1)
  File "C:\Program Files\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Program Files\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Program Files\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\instauto\api\actions\request.py", line 214, in _request
    resp = self._session.post(url, data, headers=headers)
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Traceback (most recent call last):
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Program Files\Python39\lib\http\client.py", line 331, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "C:\Program Files\Python39\lib\http\client.py", line 216, in parse_headers
    line = fp.readline(_MAXLINE + 1)
  File "C:\Program Files\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Program Files\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Program Files\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\urllib3\util\retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Program Files\Python39\lib\http\client.py", line 331, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "C:\Program Files\Python39\lib\http\client.py", line 216, in parse_headers
    line = fp.readline(_MAXLINE + 1)
  File "C:\Program Files\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Program Files\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Program Files\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\DB\Dropbox\instagramPrjct\Initial tests-v0.2\InstagramUploader.py", line 160, in <module>
    resp = client.post_post(post, 95)
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\instauto\api\actions\post.py", line 138, in post_post
    return self._request('media/configure/', Method.POST, data=as_dict, headers=headers, signed=True)
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\instauto\api\actions\request.py", line 225, in _request
    raise e
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\instauto\api\actions\request.py", line 214, in _request
    resp = self._session.post(url, data, headers=headers)
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Hamedd\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

Process finished with exit code 1

**Comment by hmdz105** [comment]
I am doing some research online on the way Instagram detects bots and automation. It seems like _IP ban_ is one of them. For newly created accounts, Instagram considers 2 or 3 posts a daily (evenly posted apart,  at different times of the day) as normal. Posting 4 or more posts in a row with similar captions is considered spamming, especially in newly created accounts. Once a user has been market as spam, its IP address is saved in a database watch list. Instagram considers all actions from that IP address and account suspicious from then on!

Right now I am able to post many stories from another IP address for the same account without a problem, but posting posts or stories with my older IP address, which was once associated with suspicious mass liking activity (using instagram_private_api) although using another Instagram profile and resulting in an action block, still gives me the  "forced disconnection" 10054 error!

**Comment by stanvanrooy** [comment]
Okay, that makes sense. It would probably be best to catch that exception and raise a more explicit one.
