### ISSUE TITLE
profile_set_picture works as image post

### ISSUE THREAD

**Issue by phlaskoo** [stanvanrooy/instauto#156]
I use bellow code to update profile picture: (windows 10 , python 3.9 , latest instauto on github)
        post=structs.post.PostFeed(pic_path,'profile picture')
        response=self.client.post_post(post,80)
        upload_id=response.json()['media']['id']
        action=profile.SetPicture(upload_id)
        status=self.client.profile_set_picture(action)

but this code only upload profile image as a post with caption ('profile picture') and also delete my bio (super weird why??)
the error that returns at the end is this:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    m.SET_PICTURE('background.jpg')
  File "C:/Users/Hosseinpour/Desktop/instabot/instabot2.py", line 56, in SET_PICTURE
    status=self.client.profile_set_picture(action)
  File "C:\Users\Hosseinpour\AppData\Local\Programs\Python\Python39\lib\site-packages\instauto\api\actions\profile.py", line 49, in profile_set_picture
    return self._request("accounts/change_profile_picture/", Method.POST, body=data)
  File "C:\Users\Hosseinpour\AppData\Local\Programs\Python\Python39\lib\site-packages\instauto\api\actions\request.py", line 60, in _request
    self._check_response_for_errors(resp)
  File "C:\Users\Hosseinpour\AppData\Local\Programs\Python\Python39\lib\site-packages\instauto\api\actions\request.py", line 105, in _check_response_for_errors
    raise BadResponse("Received a non-200 response from Instagram")
instauto.api.exceptions.BadResponse: Received a non-200 response from Instagram

**Comment by stanvanrooy** [comment]
See the updated example.

**Comment by phlaskoo** [comment]
Got it, thanks!
but still bio get empty after updating profile picture (not important at
all)
nice job

**Comment by stanvanrooy** [comment]
Could you also open a separate issue for that behaviour? Thanks! 
-------- Oorspronkelijk bericht --------Van: phlaskoo ***@***.***> Datum: 08-05-2021  13:36  (GMT+01:00) Aan: stanvanrooy/instauto ***@***.***> Cc: Stan van Rooy ***@***.***>, State change ***@***.***> Onderwerp: Re: [stanvanrooy/instauto] profile_set_picture works as image post (#156) 

Got it, thanks!

but still bio get empty after updating profile picture (not important at

all)

nice job



On Fri, May 7, 2021 at 1:36 PM Stan van Rooy ***@***.***>

wrote:
