### ISSUE TITLE
get following and followers error

### ISSUE THREAD

**Issue by phlaskoo** [stanvanrooy/instauto#158]
does not work as example and returns bellow error both for follower and following:
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    obj, result = client.followers_get(f)
  File "C:\Users\Hosseinpour\AppData\Local\Programs\Python\Python39\lib\site-packages\instauto\api\actions\friendships.py", line 35, in followers_get
    return self._get_base(obj)
  File "C:\Users\Hosseinpour\AppData\Local\Programs\Python\Python39\lib\site-packages\instauto\api\actions\friendships.py", line 81, in _get_base
    obj.max_id = as_json['next_max_id']
KeyError: 'next_max_id'

**Comment by stanvanrooy** [comment]
That error came up, in two scenarios:

1. You've retrieved all followers
2. You do not follow the account, and can't access their followers

**Comment by phlaskoo** [comment]
I am following that account and also I did not retrieve any follower or following
