### ISSUE TITLE
from_followers_of not working

### ISSUE THREAD

**Issue by alosoft** [stanvanrooy/instauto#190]
**Describe the bug**
loading followers into Bot pipelines fails

**To Reproduce**
`
>>>bot.input.from_followers_of("leomessi", 100)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Alonso\AppData\Local\Programs\Python\Python39\lib\site-packages\instauto\bot\input.py", line 43, in from_followers_of
    followers = get_followers(self._client, str(user_id), limit)
  File "C:\Users\Alonso\AppData\Local\Programs\Python\Python39\lib\site-packages\instauto\helpers\friendships.py", line 38, in get_followers
    while result and len(followers) < limit:
TypeError: '<' not supported between instances of 'int' and 'str'
`

**Expected behavior**

**Setup**
Instauto version: 2.0.1

**Comment by stanvanrooy** [comment]
Fixed and released in v2.0.2. Consider giving `instauto` a star if it helps you in any way ;)
