### ISSUE TITLE
from_followers_of returns KeyEroor

### ISSUE THREAD

**Issue by aidanMiklos** [stanvanrooy/instauto#199]
When calling from followers of the following error occurs: 
``
obj.page = data['page'] + 1
KeyError: 'page'
```
from instauto.api.client import ApiClient
from instauto.api import structs as st
from instauto.api.actions import post as ps
from instauto import bot
import os

def bruh():
  if os.path.isfile('./.instauto.save'):
      os.remove('./.instauto.save')
  if os.path.isfile('./.instauto.save'):
      client = ApiClient.initiate_from_file('./.instauto.save')
  else:
      client = ApiClient(username="BLANK", password="BLANK")
      try:
        client.log_in()
      except:
        return "Cant log in brug"
      client.save_to_disk('./.instauto.save')

  spammer = bot.Bot(username ="slavebot2.0", password="nhpam767676", client = client, delay_between_action = 2.0, delay_variance = 1.5)

  spamInput = bot.Input(client)

  spamInput.from_followers_of(account_name = "memes", limit=100)

  spammer.follow(25)
  spammer.like(50, amount=3)

  if os.path.isfile('./.instauto.save'):
      os.remove('./.instauto.save')

```

**Full debug:**

`Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/runner/SlaveSpammer-1/dcbot.py", line 20, in calling
    bruh()
  File "/home/runner/SlaveSpammer-1/instagram.py", line 24, in bruh
    spamInput.from_followers_of(account_name = "memes", limit=100)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/instauto/bot/input.py", line 42, in from_followers_of
    followers = get_followers(self._client, limit, user_id)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/instauto/helpers/friendships.py", line 40, in get_followers
    obj, result = client.followers_get(obj)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/instauto/api/actions/friendships.py", line 36, in followers_get
    return self._get_base(obj)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/instauto/api/actions/friendships.py", line 91, in _get_base
    obj.page = data['page'] + 1
KeyError: 'page'`

**Comment by aidanMiklos** [comment]
Im getting this error now

`  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/runner/SlaveSpammer-1/dcbot.py", line 20, in calling
    bruh()
  File "/home/runner/SlaveSpammer-1/instagram.py", line 30, in bruh
    spammer.start()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/instauto/bot/bot.py", line 115, in start
    accounts = self.input.filtered_accounts
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/instauto/bot/input.py", line 91, in filtered_accounts
    return list(filter(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/instauto/bot/input.py", line 92, in <lambda>
    lambda x: x['id'] not in seen and seen.append(x['id']) is None,
TypeError: 'User' object is not subscriptable`

**Comment by stanvanrooy** [comment]
Could you open a new issue for that?
