### ISSUE TITLE
Exception: Calm down

### ISSUE THREAD

**Issue by 89z** [stanvanrooy/instauto#210]
Using this program:

~~~py
from instauto.api.client import ApiClient
client = ApiClient(username='srpen6', password='PASSWORD')
client.log_in()
~~~

I get this result:

~~~
Traceback (most recent call last):
  File "D:\Desktop\ig.py", line 9, in <module>
    client.log_in()
  File "C:\python\lib\site-packages\instauto\api\actions\authentication.py", line 38, in log_in
    resp = self._request('accounts/login/', Method.POST, body=body, sign_request=True)
  File "C:\python\lib\site-packages\instauto\api\actions\request.py", line 57, in _request
    self._check_response_for_errors(resp)
  File "C:\python\lib\site-packages\instauto\api\actions\request.py", line 101, in _check_response_for_errors
    raise Exception("Calm down. Please try again in a few minutes.")
~~~

**Comment by stanvanrooy** [comment]
This exception is thrown when Instagram returns a rate limit error. Not much `instauto` can do about that.
