### ISSUE TITLE
Can't login to account and save session

### ISSUE THREAD

**Issue by yookaz97** [stanvanrooy/instauto#222]
**Describe the bug**
I can't login to instagram account and save session.

**To Reproduce**
My code:
```
import logging
logging.basicConfig()
logging.getLogger('').setLevel(logging.DEBUG)
from instauto.api.client import ApiClient

client = ApiClient(username="xxx", password="xxx")
client.log_in()

client.save_to_disk('yookaz.instauto', overwrite=True)
```

And this is error what I get in return:

```
C:\Users\yookaz\Desktop\files\instauto>py test.py
INFO:instauto.api.client:No state provided. Using default state.
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:apscheduler.scheduler:Added job "AuthenticationMixin._refresh_session" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2024-04-13 16:18:48.119336+02:00 (in 419.848303 seconds)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): i.instagram.com:443
DEBUG:urllib3.connectionpool:https://i.instagram.com:443 "GET /api/v1/zr/token/result/?device_id=android-95354edb84a8673d&token_hash=&custom_device_id=9e5e3573-9535-4edb-84a8-673dcda80de8&fetch_reason=token_expired HTTP/1.1" 200 194
DEBUG:urllib3.connectionpool:Resetting dropped connection: i.instagram.com
DEBUG:urllib3.connectionpool:https://i.instagram.com:443 "POST /api/v1/qe/sync/ HTTP/1.1" 200 711
DEBUG:urllib3.connectionpool:Resetting dropped connection: i.instagram.com
DEBUG:urllib3.connectionpool:https://i.instagram.com:443 "POST /api/v1/accounts/login/ HTTP/1.1" 400 161
Traceback (most recent call last):
  File "C:\Users\yookaz\Desktop\files\instauto\test.py", line 7, in <module>
    client.log_in()
  File "C:\Users\yookaz\AppData\Local\Programs\Python\Python39\lib\site-packages\instauto\api\actions\authentication.py", line 38, in log_in
    resp = self._request('accounts/login/', Method.POST, body=body, sign_request=True)
  File "C:\Users\yookaz\AppData\Local\Programs\Python\Python39\lib\site-packages\instauto\api\actions\request.py", line 57, in _request
    self._check_response_for_errors(resp)
  File "C:\Users\yookaz\AppData\Local\Programs\Python\Python39\lib\site-packages\instauto\api\actions\request.py", line 103, in _check_response_for_errors
    raise BadResponse(
instauto.api.exceptions.BadResponse: Received a non-200 response from Instagram:             Je moet Instagram bijwerken naar de nieuwste versie voordat je de app kunt gebruiken.
```

**Setup**
Instauto version: v2.0.7 because I can't upgrade via pip (ERROR: No matching distribution found for instauto==2.0.8)

**Comment by stanvanrooy** [comment]
@yookaz97 this is the resolved in the latest version, just published to PyPi (V2.1.0). Please try upgrading (`pip install instauto --upgrade`) and try again.
