### ISSUE TITLE
Weird syntax error on raspberry pi

### ISSUE THREAD

**Issue by marvic2409** [stanvanrooy/instauto#43]
I installed all the requirements and the library and when I try importing it I get this error:
`Traceback (most recent call last):
  File "insta.py", line 13, in <module>
    from instauto import ApiClient
  File "/home/pi/.local/lib/python3.7/site-packages/instauto/__init__.py", line 2, in <module>
    from .api.client import ApiClient
  File "/home/pi/.local/lib/python3.7/site-packages/instauto/api/client.py", line 16, in <module>
    from .actions import AuthenticationMixIn, PostMixin, RequestMixIn, ProfileMixin, FriendshipsMixin, SearchMixin
  File "/home/pi/.local/lib/python3.7/site-packages/instauto/api/actions/__init__.py", line 3, in <module>
    from .request import RequestMixIn
  File "/home/pi/.local/lib/python3.7/site-packages/instauto/api/actions/request.py", line 93
    if www_claim := headers.get('ig-set-www-claim'): self.state.www_claim = www_claim
                  ^
SyntaxError: invalid syntax
`

**Comment by stanvanrooy** [comment]
`instauto` is only compatible with python3.8+ right now, but I think it's a good idea to lower that to 3.6+. 

I believe that would be as simple as removing the usages of the walrus operator. Feel free to submit a PR :)

**Comment by marvic2409** [comment]
Thanks for responding at such an early time. Literally a legend

**Comment by stanvanrooy** [comment]
No problem. Lmk if there's anything else
