### ISSUE TITLE
ImportError: cannot import name 'Protocol'

### ISSUE THREAD

**Issue by skiesx** [stanvanrooy/instauto#74]
Hi)

When i run code

```
import random
import os
os.environ['TZ']= 'Europe/Kiev'
from time import sleep

from instauto.api.client import ApiClient

if os.path.isfile('./.instauto.save'):
    client = ApiClient.initiate_from_file('./.instauto.save')
else:
    client = ApiClient(user_name=os.environ.get("INSTAUTO_USER") or "username", password=os.environ.get("INSTAUTO_PASS") or "pass")
    client.login()
    client.save_to_disk('./.instauto.save')
```
i get an error

```
Traceback (most recent call last):
  File "instauto_test.py", line 6, in <module>
    from instauto.api.client import ApiClient
  File "..../lib/python3.6/site-packages/instauto/api/client.py", line 16, in <module>
    from .actions.profile import ProfileMixin
  File ".../lib/python3.6/site-packages/instauto/api/actions/profile.py", line 3, in <module>
    from instauto.api.actions.stubs import _request
  File ".../lib/python3.6/site-packages/instauto/api/actions/stubs.py", line 3, in <module>
    from typing import Protocol, Dict
ImportError: cannot import name 'Protocol'
```
cannot import "Protocol"

Help me solve this problem

**Comment by stanvanrooy** [comment]
Hmm, `Protocol` is probably introduced in python3.8, so that small part needs to be made python3.6 compatible.

**Comment by zecloud** [comment]
Same problem here with Python3.7
